name: movabletype/mt-rich-text-editor
on:
  push:
    branches:
      - "**/*"
    tags:
      - "v*"
      - "*@v*"
  pull_request:
    types: [opened, synchronize]

jobs:
  perl:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { image: cloud7 }
          - { image: buster }
          - { image: bullseye }
          - { image: fedora35 }
          - { image: fedora37 }
          - { image: fedora40 }
          - { image: fedora41 }
          - { image: fedora42 }
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: movabletype/internal-movabletype
          token: ${{ secrets.FETCH_INTERNAL }}
          ref: develop9
          path: mt
      - uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Run tests
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/mt:/app \
            -v ${{ github.workspace }}/packages/plugin/plugins/MTRichTextEditor:/app/plugins/MTRichTextEditor \
            -v ${{ github.workspace }}/packages/plugin/plugins/FormattedTextForMTRichTextEditor:/app/plugins/FormattedTextForMTRichTextEditor \
            -w /app \
            ghcr.io/movabletype/movabletype/test:${{ matrix.config.image }} \
          prove -j4 -PMySQLPool=MT::Test::Env -It/lib \
            plugins/MTRichTextEditor/t \
            plugins/FormattedTextForMTRichTextEditor/t

  node:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "22"

      - name: Install libs
        run: sudo apt-get install --no-install-recommends -y libjson-perl libyaml-perl zip

      - name: Install @rollup/rollup-linux-x64-gnu explicitly
        run: npm install @rollup/rollup-linux-x64-gnu --save-optional

      - name: Install dependencies
        run: npm install -ws

      - name: Build locales
        run: npm run build:locales

      - name: Run lint
        run: npm run lint -ws

      - name: Run format
        run: npm run format -ws

      - name: Run tests
        run: npm run test:unit -ws -- --run

  build:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "22"

      - name: Install libs
        run: sudo apt-get install --no-install-recommends -y libjson-perl libyaml-perl zip

      - name: Install @rollup/rollup-linux-x64-gnu explicitly
        run: npm install @rollup/rollup-linux-x64-gnu --save-optional

      - name: Build plugin
        run: npm run build

      - name: Upload all plugins
        id: upload-all-plugins
        uses: actions/upload-artifact@v4
        with:
          name: plugin
          path: |
            packages/plugin/dist

      - name: Upload tarball
        id: upload-tarball
        uses: actions/upload-artifact@v4
        with:
          name: tarball
          path: |
            packages/plugin/dist/*.tar.gz

      - name: Add comment to PR
        uses: peter-evans/create-or-update-comment@71345be0265236311c031f5c7866368bd1eff043
        if: ${{ github.event_name == 'pull_request' }}
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ### Download Links
            
            You can download the build artifacts from the following links:

            - **All Plugins**: [Download from Actions Artifacts](${{ steps.upload-all-plugins.outputs.artifact-url }})
            - **Tarball**: [Download from Actions Artifacts](${{ steps.upload-tarball.outputs.artifact-url }})

      - name: Upload package to GitHub Releases
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        uses: softprops/action-gh-release@72f2c25fcb47643c292f7107632f7a47c1df5cd8
        with:
          draft: true
          files: |
            packages/plugin/dist/*.zip
            packages/plugin/dist/*.tar.gz
