name: movabletype/mt-rich-text-editor
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "22"

      - name: Install libs
        run: sudo apt-get install --no-install-recommends -y libjson-perl libyaml-perl zip

      - name: Install @rollup/rollup-linux-x64-gnu explicitly
        run: npm install @rollup/rollup-linux-x64-gnu --save-optional

      - name: Install dependencies
        run: npm install -ws

      - name: Run lint
        run: npm run lint -ws

      - name: Run format
        run: npm run format -ws

      - name: Build plugin
        env:
          NODE_ENV: production
        run: npm run build

      - name: Run tests
        run: npm run test:unit -ws -- --run

      - name: Archive plugin
        uses: actions/upload-artifact@v4
        with:
          name: plugin
          path: |
            packages/plugin/dist
