name: movabletype/mt-rich-text-editor
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "22"

      - name: Install libs
        run: sudo apt-get install --no-install-recommends -y libjson-perl libyaml-perl zip

      - name: Install @rollup/rollup-linux-x64-gnu explicitly
        run: npm install @rollup/rollup-linux-x64-gnu --save-optional

      - name: Install dependencies
        run: npm install -ws

      - name: Build locales
        run: npm run build:locales

      - name: Run lint
        run: npm run lint -ws

      - name: Run format
        run: npm run format -ws

      - name: Run tests
        run: npm run test:unit -ws -- --run

  build:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "22"

      - name: Install libs
        run: sudo apt-get install --no-install-recommends -y libjson-perl libyaml-perl zip

      - name: Install @rollup/rollup-linux-x64-gnu explicitly
        run: npm install @rollup/rollup-linux-x64-gnu --save-optional

      - name: Build plugin
        run: npm run build

      - name: Upload tarball
        id: upload-tarball
        uses: actions/upload-artifact@v4
        with:
          name: tarball
          path: |
            packages/plugin/dist/*.tar.gz

      - name: Upload zip
        id: upload-zip
        uses: actions/upload-artifact@v4
        with:
          name: zip
          path: |
            packages/plugin/dist/*.zip

      - name: Add comment to PR
        uses: peter-evans/create-or-update-comment@71345be0265236311c031f5c7866368bd1eff043
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ### Download Links
            
            You can download the build artifacts from the following links:
            
            - **Tarball**: [Download from Actions Artifacts](${{ steps.upload-tarball.outputs.artifact-url }})
            - **Zip**: [Download from Actions Artifacts](${{ steps.upload-zip.outputs.artifact-url }})
